In [1]:
import numpy as np

In [44]:
def LUDecomp(A):
    M, N = A.shape
    print("# Shape of A : {} {}".format(M, N))
    
    if M == 1:
        return A

    for i in range(1,M):
        A[i,0] = A[i,0]/A[0,0]
        
    if N == 1:
        return A
    
    A[1:,1:] = A[1:,1:] - np.outer(A[1:,0],A[0,1:])
    
    A[1:,1:] = LUDecomp(A[1:,1:])
        
    return A

def getLU(A):
    M, N = A.shape
    L = np.zeros( (M, N))
    U = np.zeros( (N, N))
    
    for i in range(N):
        L[i,i] = 1
        L[i+1:,i] = A[i+1:,i]
        U[i,i:] = A[i, i:]
    return L, U

In [45]:
A = np.array([[2,1,1,0],[4,3,3,1],[8,7,9,5],[6,7,9,8]])
print(A)
A = LUDecomp(A)
print(A)
L, U = getLU(A)
print(L)
print(U)

[[2 1 1 0]
 [4 3 3 1]
 [8 7 9 5]
 [6 7 9 8]]
# Shape of A : 4 4
# Shape of A : 3 3
# Shape of A : 2 2
# Shape of A : 1 1
[[2 1 1 0]
 [2 1 1 1]
 [4 3 2 2]
 [3 4 1 2]]
[[1. 0. 0. 0.]
 [2. 1. 0. 0.]
 [4. 3. 1. 0.]
 [3. 4. 1. 1.]]
[[2. 1. 1. 0.]
 [0. 1. 1. 1.]
 [0. 0. 2. 2.]
 [0. 0. 0. 2.]]


In [46]:
L + U - np.eye(4) - A

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
np.dot(L, U)

array([[2., 1., 1., 0.],
       [4., 3., 3., 1.],
       [8., 7., 9., 5.],
       [6., 7., 9., 8.]])

In [64]:
M = 15; N = 4
#np.random.seed(1234)
A = np.random.random((M,N))
L, U = getLU(LUDecomp(A.copy()))
print(A[0,0])
#print(L)
#print(U)
np.allclose(np.dot(L, U), A)

# Shape of A : 15 4
# Shape of A : 14 3
# Shape of A : 13 2
# Shape of A : 12 1
0.04190139877173671


True

True